networks:
  psqlnet:
    driver: bridge

services:

  mavendb-psql:
    image: postgres:18
    hostname: mavendb-psql
    container_name: mavendb-psql
    restart: always
    environment:
      POSTGRES_USER: mavendbadmin
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: mavendb
    ports:
      - ${PSQL_PORT}:5432
    command: >
      postgres 
      -c checkpoint_completion_target=0.9
      -c checkpoint_timeout=30min
      -c fsync=off
      -c full_page_writes=off
      -c effective_cache_size=96GB
      -c maintenance_work_mem=8GB
      -c max_wal_size=64GB
      -c min_wal_size=8GB
      -c random_page_cost=1.1
      -c shared_buffers=32GB
      -c synchronous_commit=off
      -c wal_buffers=128MB
      -c work_mem=64MB
    shm_size: 16gb
    networks:
      - psqlnet

  mavendb-psql-adminer:
    image: adminer
    hostname: mavendb-psql-adminer
    container_name: mavendb-psql-adminer
    restart: always
    depends_on:
      - mavendb-psql
    environment:
      ADMINER_DEFAULT_SERVER: 'mavendb-psql'
    ports:
      - ${PSQL_ADMINER_PORT}:8080
    networks:
      - psqlnet

