networks:
  postgresnet:
    driver: bridge

services:

  postgresdb:
    image: postgres:18
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: mavendbadmin
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: mavendb
    ports:
      - ${POSTGRES_PORT}:5432
    command: >
      postgres 
      -c shared_buffers=32GB
      -c effective_cache_size=96GB
      -c work_mem=256MB
      -c maintenance_work_mem=8GB
      -c min_wal_size=4GB
      -c max_wal_size=16GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c random_page_cost=1.1
    shm_size: 16gb
    networks:
      - postgresnet

  postgres-adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: 'postgresdb'
    ports:
      - ${POSTGRES_ADMINER_PORT}:8080
    networks:
      - postgresnet

