networks:
  mavendbmysqlnet:
    driver: bridge

services:

  # Mavendb Database
  mysqldb:
    image: mysql:8
    # Buffer Pool Settings based on OS RAM Size
    #   OS RAM :  innodb_buffer_pool_size
    #    16 GB                        10G
    #    32 GB                        20G
    #    64 GB                        40G
    #   128 GB                       100G
    #
    # innodb_flush_log_at_trx_commit:
    #   For batch operations where absolute ACID compliance for every single intermediate write is not critical, setting this to 0 or 2 can improve write performance, though at the risk of losing a few seconds of data in a crash.
    command:
      --bulk_insert_buffer_size=128M
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --default-time-zone='+00:00'
      --disable-log-bin
      --group_concat_max_len=52428800
      --innodb_buffer_pool_size=100G
      --innodb_doublewrite=0
      --innodb_file_per_table=1
      --innodb_flush_log_at_timeout=4
      --innodb_flush_log_at_trx_commit=2
      --innodb_log_buffer_size=256M
      --innodb_log_file_size=1G
      --innodb_log_files_in_group=4
      --innodb_sort_buffer_size=512M
      --local_infile=1
      --log_queries_not_using_indexes=1
      --long_query_time=2
      --max_connections=100
      --max_heap_table_size=5G
      --mysql_native_password=ON
      --read_rnd_buffer_size=512M
      --slow_query_log=1
      --skip-name-resolve
      --sort_buffer_size=512M
      --tmp_table_size=5G
      --temptable_max_ram=5G
    hostname: mavendb-mysql
    container_name: mavendb-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mavendb'
      MYSQL_USER: "${MYSQL_USER}"
      # Passwords are subjected to be changed based on your requirement
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      # Where dump data will be stored
      - ./mysql-files:/var/lib/mysql-files
    deploy:
      resources:
        reservations:
          memory: 10240M
    expose:
      # Opens port 3306 on the container inside the docker network
      - '3306'
    ports:
      # Map docker MySQL port to hosting machine
      - ${MYSQL_PORT}:3306
    networks:
      - mavendbmysqlnet
 
  # Database Admin Tool
  mysql-adminer:
    image: adminer
    hostname: mavendb-adminer
    container_name: mavendb-adminer
    restart: always
    environment:
      # Hostname of the DB Image
      ADMINER_DEFAULT_SERVER: 'mysqldb'
    depends_on:
      - mysqldb
    ports:
      - ${MYSQL_ADMINER_PORT}:8080
    networks:
      - mavendbmysqlnet

  # Rest API
  mysql-mavendb-api:
    image: mevdschee/php-crud-api
    hostname: mavendb-api
    container_name: mavendb-api
    environment:
      PHP_CRUD_API_DRIVER: 'mysql'
      PHP_CRUD_API_ADDRESS: 'mysqldb'
      PHP_CRUD_API_PORT: 3306
      PHP_CRUD_API_DATABASE: 'mavendb'
      PHP_CRUD_API_TABLES: 'gav'
      PHP_CRUD_API_USERNAME: "${MYSQL_USER}"
      PHP_CRUD_API_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      PHP_CRUD_API_DEBUG: 1
    ports:
      - "2080:80"
    networks:
      - mavendbmysqlnet
