networks:
  psqlnet:
    driver: bridge

services:

  postgresdb:
    image: postgres:18
    hostname: mavendb-psql
    container_name: mavendb-psql
    restart: always
    environment:
      POSTGRES_USER: mavendbadmin
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: mavendb
    ports:
      - ${PSQL_PORT}:5432
    command: >
      postgres 
      -c shared_buffers=32GB
      -c effective_cache_size=96GB
      -c work_mem=256MB
      -c maintenance_work_mem=8GB
      -c min_wal_size=4GB
      -c max_wal_size=16GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c random_page_cost=1.1
    shm_size: 16gb
    networks:
      - psqlnet

  postgres-adminer:
    image: adminer
    hostname: mavendb-psql-adminer
    container_name: mavendb-psql-adminer
    restart: always
    depends_on:
      - postgresdb
    environment:
      ADMINER_DEFAULT_SERVER: 'mavendb-psql'
    ports:
      - ${PSQL_ADMINER_PORT}:8080
    networks:
      - psqlnet

