#
# MySQL Properties
#

org.mavendb.mysql.url=jdbc:mysql://127.0.0.1:3306/mavendb
org.mavendb.mysql.user=mavendbadmin
org.mavendb.mysql.password=123456
#org.mavendb.mysql.batch.size=10000

#
# MongoDB Properties
#
org.mavendb.mongodb.url=mongodb://root:123456@localhost:27017/?maxPoolSize=100&minPoolSize=4
# org.mavendb.mongodb.database.name=mavendb
# org.mavendb.mongodb.batch.size=20000

#
# PSQL Properties
#
org.mavendb.psql.url=jdbc:postgresql://127.0.0.1:5432/mavendb
org.mavendb.psql.user=mavendbadmin
org.mavendb.psql.password=123456
# org.mavendb.psql.batch.size=10000

#
# Maximum number of concurrent virtual threads
#
# - Default number is available processors
#org.mavendb.thread.pool.size=4